# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61807bd94b7dd990bfe11554ac714c67f49e0206e4774abcb2fd5dfaa2f337e3946eaa41155212cfb4170180efc584f42faba43bf10c099c5f644e270e0298ba

test:
  secret_key_base: f1b302b931b66fd0450ad97244cabe4185f472ff0e94c77d83d81ea9ff5988440d8e260e65423bbe6159ac9664cbbeb7669a55f33eff80c47972fe5bbf15ae08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
